root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
# 単なる古いシェルコマンド。`make`を使用することもできます。
cmd = "go build -o ./tmp/main ./main.go"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "APP_USER=air dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec --continue ./tmp/main"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "500s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
# ビルドエラーが発生したら、古いバイナリの実行を停止します。
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
# 終了時にtmpディレクトリを削除します
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true